add_test( is_same_template /home/kimdoyoung/Desktop/work/gapp/build/unit_tests is_same_template  )
set_tests_properties( is_same_template PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( is_one_of_templates /home/kimdoyoung/Desktop/work/gapp/build/unit_tests is_one_of_templates  )
set_tests_properties( is_one_of_templates PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( nth_type /home/kimdoyoung/Desktop/work/gapp/build/unit_tests nth_type  )
set_tests_properties( nth_type PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( is_derived_from_spec_of /home/kimdoyoung/Desktop/work/gapp/build/unit_tests is_derived_from_spec_of  )
set_tests_properties( is_derived_from_spec_of PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( is_specialization_of /home/kimdoyoung/Desktop/work/gapp/build/unit_tests is_specialization_of  )
set_tests_properties( is_specialization_of PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( is_reverse_iterator /home/kimdoyoung/Desktop/work/gapp/build/unit_tests is_reverse_iterator  )
set_tests_properties( is_reverse_iterator PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( dereference /home/kimdoyoung/Desktop/work/gapp/build/unit_tests dereference  )
set_tests_properties( dereference PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( remove_rvalue_ref /home/kimdoyoung/Desktop/work/gapp/build/unit_tests remove_rvalue_ref  )
set_tests_properties( remove_rvalue_ref PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( copy_const_t /home/kimdoyoung/Desktop/work/gapp/build/unit_tests copy_const_t  )
set_tests_properties( copy_const_t PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( concurrent_queue /home/kimdoyoung/Desktop/work/gapp/build/unit_tests concurrent_queue  )
set_tests_properties( concurrent_queue PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( thread_pool /home/kimdoyoung/Desktop/work/gapp/build/unit_tests thread_pool  )
set_tests_properties( thread_pool PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( parallel_for /home/kimdoyoung/Desktop/work/gapp/build/unit_tests parallel_for  )
set_tests_properties( parallel_for PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( nested_parallel_for /home/kimdoyoung/Desktop/work/gapp/build/unit_tests nested_parallel_for  )
set_tests_properties( nested_parallel_for PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( spinlock /home/kimdoyoung/Desktop/work/gapp/build/unit_tests spinlock  )
set_tests_properties( spinlock PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( shared_spinlock /home/kimdoyoung/Desktop/work/gapp/build/unit_tests shared_spinlock  )
set_tests_properties( shared_spinlock PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( roulette_selection /home/kimdoyoung/Desktop/work/gapp/build/unit_tests roulette_selection  )
set_tests_properties( roulette_selection PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( tournament_selection /home/kimdoyoung/Desktop/work/gapp/build/unit_tests tournament_selection  )
set_tests_properties( tournament_selection PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( rank_selection /home/kimdoyoung/Desktop/work/gapp/build/unit_tests rank_selection  )
set_tests_properties( rank_selection PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[sigma_selection[selection][single-objective]]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[sigma_selection\[selection\]\[single-objective\]]==]  )
set_tests_properties( [==[sigma_selection[selection][single-objective]]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[boltzmann_selection[selection][single-objective]]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[boltzmann_selection\[selection\]\[single-objective\]]==]  )
set_tests_properties( [==[boltzmann_selection[selection][single-objective]]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( scope_exit /home/kimdoyoung/Desktop/work/gapp/build/unit_tests scope_exit  )
set_tests_properties( scope_exit PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( restore_on_exit /home/kimdoyoung/Desktop/work/gapp/build/unit_tests restore_on_exit  )
set_tests_properties( restore_on_exit PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( random_int /home/kimdoyoung/Desktop/work/gapp/build/unit_tests random_int  )
set_tests_properties( random_int PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( random_real /home/kimdoyoung/Desktop/work/gapp/build/unit_tests random_real  )
set_tests_properties( random_real PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( random_binomial /home/kimdoyoung/Desktop/work/gapp/build/unit_tests random_binomial  )
set_tests_properties( random_binomial PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( random_idx /home/kimdoyoung/Desktop/work/gapp/build/unit_tests random_idx  )
set_tests_properties( random_idx PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( random_element /home/kimdoyoung/Desktop/work/gapp/build/unit_tests random_element  )
set_tests_properties( random_element PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( sample_unique /home/kimdoyoung/Desktop/work/gapp/build/unit_tests sample_unique  )
set_tests_properties( sample_unique PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[sample_unique_bounds_8 - std::int8_t]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[sample_unique_bounds_8 - std::int8_t]==]  )
set_tests_properties( [==[sample_unique_bounds_8 - std::int8_t]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[sample_unique_bounds_8 - std::uint8_t]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[sample_unique_bounds_8 - std::uint8_t]==]  )
set_tests_properties( [==[sample_unique_bounds_8 - std::uint8_t]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[sample_unique_bounds_64 - std::int64_t]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[sample_unique_bounds_64 - std::int64_t]==]  )
set_tests_properties( [==[sample_unique_bounds_64 - std::int64_t]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[sample_unique_bounds_64 - std::uint64_t]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[sample_unique_bounds_64 - std::uint64_t]==]  )
set_tests_properties( [==[sample_unique_bounds_64 - std::uint64_t]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( replacement_best /home/kimdoyoung/Desktop/work/gapp/build/unit_tests replacement_best  )
set_tests_properties( replacement_best PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( replacement_children /home/kimdoyoung/Desktop/work/gapp/build/unit_tests replacement_children  )
set_tests_properties( replacement_children PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( replacement_elitism /home/kimdoyoung/Desktop/work/gapp/build/unit_tests replacement_elitism  )
set_tests_properties( replacement_elitism PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[reference_lines - quasirandomSimplexPointsMirror]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[reference_lines - quasirandomSimplexPointsMirror]==]  )
set_tests_properties( [==[reference_lines - quasirandomSimplexPointsMirror]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[reference_lines - quasirandomSimplexPointsSort]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[reference_lines - quasirandomSimplexPointsSort]==]  )
set_tests_properties( [==[reference_lines - quasirandomSimplexPointsSort]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[reference_lines - quasirandomSimplexPointsRoot]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[reference_lines - quasirandomSimplexPointsRoot]==]  )
set_tests_properties( [==[reference_lines - quasirandomSimplexPointsRoot]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[reference_lines - quasirandomSimplexPointsLog]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[reference_lines - quasirandomSimplexPointsLog]==]  )
set_tests_properties( [==[reference_lines - quasirandomSimplexPointsLog]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[reference_lines_subset - quasirandomSimplexPointsMirror]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[reference_lines_subset - quasirandomSimplexPointsMirror]==]  )
set_tests_properties( [==[reference_lines_subset - quasirandomSimplexPointsMirror]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[reference_lines_subset - quasirandomSimplexPointsSort]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[reference_lines_subset - quasirandomSimplexPointsSort]==]  )
set_tests_properties( [==[reference_lines_subset - quasirandomSimplexPointsSort]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[reference_lines_subset - quasirandomSimplexPointsRoot]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[reference_lines_subset - quasirandomSimplexPointsRoot]==]  )
set_tests_properties( [==[reference_lines_subset - quasirandomSimplexPointsRoot]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[reference_lines_subset - quasirandomSimplexPointsLog]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[reference_lines_subset - quasirandomSimplexPointsLog]==]  )
set_tests_properties( [==[reference_lines_subset - quasirandomSimplexPointsLog]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( qrng /home/kimdoyoung/Desktop/work/gapp/build/unit_tests qrng  )
set_tests_properties( qrng PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[single_objective_problems - Sphere]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[single_objective_problems - Sphere]==]  )
set_tests_properties( [==[single_objective_problems - Sphere]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[single_objective_problems - Rastrigin]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[single_objective_problems - Rastrigin]==]  )
set_tests_properties( [==[single_objective_problems - Rastrigin]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[single_objective_problems - Rosenbrock]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[single_objective_problems - Rosenbrock]==]  )
set_tests_properties( [==[single_objective_problems - Rosenbrock]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[single_objective_problems - Schwefel]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[single_objective_problems - Schwefel]==]  )
set_tests_properties( [==[single_objective_problems - Schwefel]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[single_objective_problems - Griewank]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[single_objective_problems - Griewank]==]  )
set_tests_properties( [==[single_objective_problems - Griewank]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[single_objective_problems - Ackley]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[single_objective_problems - Ackley]==]  )
set_tests_properties( [==[single_objective_problems - Ackley]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[single_objective_problems - Levy]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[single_objective_problems - Levy]==]  )
set_tests_properties( [==[single_objective_problems - Levy]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( kursawe /home/kimdoyoung/Desktop/work/gapp/build/unit_tests kursawe  )
set_tests_properties( kursawe PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[zdt_suite - ZDT1]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[zdt_suite - ZDT1]==]  )
set_tests_properties( [==[zdt_suite - ZDT1]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[zdt_suite - ZDT2]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[zdt_suite - ZDT2]==]  )
set_tests_properties( [==[zdt_suite - ZDT2]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[zdt_suite - ZDT3]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[zdt_suite - ZDT3]==]  )
set_tests_properties( [==[zdt_suite - ZDT3]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[zdt_suite - ZDT4]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[zdt_suite - ZDT4]==]  )
set_tests_properties( [==[zdt_suite - ZDT4]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[zdt_suite - ZDT5]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[zdt_suite - ZDT5]==]  )
set_tests_properties( [==[zdt_suite - ZDT5]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[zdt_suite - ZDT6]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[zdt_suite - ZDT6]==]  )
set_tests_properties( [==[zdt_suite - ZDT6]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[dtlz_suite - DTLZ1]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[dtlz_suite - DTLZ1]==]  )
set_tests_properties( [==[dtlz_suite - DTLZ1]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[dtlz_suite - DTLZ2]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[dtlz_suite - DTLZ2]==]  )
set_tests_properties( [==[dtlz_suite - DTLZ2]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[dtlz_suite - DTLZ3]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[dtlz_suite - DTLZ3]==]  )
set_tests_properties( [==[dtlz_suite - DTLZ3]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[dtlz_suite - DTLZ4]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[dtlz_suite - DTLZ4]==]  )
set_tests_properties( [==[dtlz_suite - DTLZ4]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[dtlz_suite - DTLZ5]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[dtlz_suite - DTLZ5]==]  )
set_tests_properties( [==[dtlz_suite - DTLZ5]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[dtlz_suite - DTLZ6]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[dtlz_suite - DTLZ6]==]  )
set_tests_properties( [==[dtlz_suite - DTLZ6]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[dtlz_suite - DTLZ7]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[dtlz_suite - DTLZ7]==]  )
set_tests_properties( [==[dtlz_suite - DTLZ7]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( probability /home/kimdoyoung/Desktop/work/gapp/build/unit_tests probability  )
set_tests_properties( probability PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( merge_pareto_sets /home/kimdoyoung/Desktop/work/gapp/build/unit_tests merge_pareto_sets  )
set_tests_properties( merge_pareto_sets PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( find_pareto_front_1D /home/kimdoyoung/Desktop/work/gapp/build/unit_tests find_pareto_front_1D  )
set_tests_properties( find_pareto_front_1D PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[find_pareto_front_nd - findParetoFrontSort]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[find_pareto_front_nd - findParetoFrontSort]==]  )
set_tests_properties( [==[find_pareto_front_nd - findParetoFrontSort]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[find_pareto_front_nd - findParetoFrontBest]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[find_pareto_front_nd - findParetoFrontBest]==]  )
set_tests_properties( [==[find_pareto_front_nd - findParetoFrontBest]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[find_pareto_front_nd - findParetoFrontKung]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[find_pareto_front_nd - findParetoFrontKung]==]  )
set_tests_properties( [==[find_pareto_front_nd - findParetoFrontKung]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[nd_sort - fastNonDominatedSort]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[nd_sort - fastNonDominatedSort]==]  )
set_tests_properties( [==[nd_sort - fastNonDominatedSort]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[nd_sort - dominanceDegreeSort]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[nd_sort - dominanceDegreeSort]==]  )
set_tests_properties( [==[nd_sort - dominanceDegreeSort]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( mutation_fitness_eval /home/kimdoyoung/Desktop/work/gapp/build/unit_tests mutation_fitness_eval  )
set_tests_properties( mutation_fitness_eval PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[binary_mutation - binary::Flip]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[binary_mutation - binary::Flip]==]  )
set_tests_properties( [==[binary_mutation - binary::Flip]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[real_mutation - real::Boundary]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[real_mutation - real::Boundary]==]  )
set_tests_properties( [==[real_mutation - real::Boundary]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[real_mutation - real::Gauss]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[real_mutation - real::Gauss]==]  )
set_tests_properties( [==[real_mutation - real::Gauss]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[real_mutation - real::NonUniform]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[real_mutation - real::NonUniform]==]  )
set_tests_properties( [==[real_mutation - real::NonUniform]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[real_mutation - real::Polynomial]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[real_mutation - real::Polynomial]==]  )
set_tests_properties( [==[real_mutation - real::Polynomial]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[real_mutation - real::Uniform]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[real_mutation - real::Uniform]==]  )
set_tests_properties( [==[real_mutation - real::Uniform]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[perm_mutation - perm::Inversion]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[perm_mutation - perm::Inversion]==]  )
set_tests_properties( [==[perm_mutation - perm::Inversion]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[perm_mutation - perm::Shift]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[perm_mutation - perm::Shift]==]  )
set_tests_properties( [==[perm_mutation - perm::Shift]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[perm_mutation - perm::Shuffle]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[perm_mutation - perm::Shuffle]==]  )
set_tests_properties( [==[perm_mutation - perm::Shuffle]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[perm_mutation - perm::Swap2]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[perm_mutation - perm::Swap2]==]  )
set_tests_properties( [==[perm_mutation - perm::Swap2]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[perm_mutation - perm::Swap3]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[perm_mutation - perm::Swap3]==]  )
set_tests_properties( [==[perm_mutation - perm::Swap3]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[integer_mutation - integer::Uniform]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[integer_mutation - integer::Uniform]==]  )
set_tests_properties( [==[integer_mutation - integer::Uniform]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[fitness_metrics - FitnessMin]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[fitness_metrics - FitnessMin]==]  )
set_tests_properties( [==[fitness_metrics - FitnessMin]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[fitness_metrics - FitnessMax]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[fitness_metrics - FitnessMax]==]  )
set_tests_properties( [==[fitness_metrics - FitnessMax]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[fitness_metrics - FitnessMean]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[fitness_metrics - FitnessMean]==]  )
set_tests_properties( [==[fitness_metrics - FitnessMean]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[fitness_metrics - FitnessVariance]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[fitness_metrics - FitnessVariance]==]  )
set_tests_properties( [==[fitness_metrics - FitnessVariance]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[fitness_metrics - FitnessStdDev]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[fitness_metrics - FitnessStdDev]==]  )
set_tests_properties( [==[fitness_metrics - FitnessStdDev]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[fitness_metrics - NadirPoint]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[fitness_metrics - NadirPoint]==]  )
set_tests_properties( [==[fitness_metrics - NadirPoint]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( nadir_point_metric /home/kimdoyoung/Desktop/work/gapp/build/unit_tests nadir_point_metric  )
set_tests_properties( nadir_point_metric PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( hypervolume_metric /home/kimdoyoung/Desktop/work/gapp/build/unit_tests hypervolume_metric  )
set_tests_properties( hypervolume_metric PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( hypervolume_auto /home/kimdoyoung/Desktop/work/gapp/build/unit_tests hypervolume_auto  )
set_tests_properties( hypervolume_auto PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( fitness_evaluations /home/kimdoyoung/Desktop/work/gapp/build/unit_tests fitness_evaluations  )
set_tests_properties( fitness_evaluations PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( matrix /home/kimdoyoung/Desktop/work/gapp/build/unit_tests matrix  )
set_tests_properties( matrix PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( matrix_rows /home/kimdoyoung/Desktop/work/gapp/build/unit_tests matrix_rows  )
set_tests_properties( matrix_rows PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( matrix_algorithms /home/kimdoyoung/Desktop/work/gapp/build/unit_tests matrix_algorithms  )
set_tests_properties( matrix_algorithms PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( fp_compare /home/kimdoyoung/Desktop/work/gapp/build/unit_tests fp_compare  )
set_tests_properties( fp_compare PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( pareto_compare_less /home/kimdoyoung/Desktop/work/gapp/build/unit_tests pareto_compare_less  )
set_tests_properties( pareto_compare_less PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( pareto_compare_three_way /home/kimdoyoung/Desktop/work/gapp/build/unit_tests pareto_compare_three_way  )
set_tests_properties( pareto_compare_three_way PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( euclidean_norm /home/kimdoyoung/Desktop/work/gapp/build/unit_tests euclidean_norm  )
set_tests_properties( euclidean_norm PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( normalize /home/kimdoyoung/Desktop/work/gapp/build/unit_tests normalize  )
set_tests_properties( normalize PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( euclidean_distance /home/kimdoyoung/Desktop/work/gapp/build/unit_tests euclidean_distance  )
set_tests_properties( euclidean_distance PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( perpendicular_distance /home/kimdoyoung/Desktop/work/gapp/build/unit_tests perpendicular_distance  )
set_tests_properties( perpendicular_distance PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( volume_between /home/kimdoyoung/Desktop/work/gapp/build/unit_tests volume_between  )
set_tests_properties( volume_between PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( integral_sin_pow /home/kimdoyoung/Desktop/work/gapp/build/unit_tests integral_sin_pow  )
set_tests_properties( integral_sin_pow PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( stable_iterator /home/kimdoyoung/Desktop/work/gapp/build/unit_tests stable_iterator  )
set_tests_properties( stable_iterator PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( iota_iterator /home/kimdoyoung/Desktop/work/gapp/build/unit_tests iota_iterator  )
set_tests_properties( iota_iterator PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( indestructible /home/kimdoyoung/Desktop/work/gapp/build/unit_tests indestructible  )
set_tests_properties( indestructible PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( hypervolume /home/kimdoyoung/Desktop/work/gapp/build/unit_tests hypervolume  )
set_tests_properties( hypervolume PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( map /home/kimdoyoung/Desktop/work/gapp/build/unit_tests map  )
set_tests_properties( map PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( flatten /home/kimdoyoung/Desktop/work/gapp/build/unit_tests flatten  )
set_tests_properties( flatten PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( arithmetic_funcs /home/kimdoyoung/Desktop/work/gapp/build/unit_tests arithmetic_funcs  )
set_tests_properties( arithmetic_funcs PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( comparison_funcs /home/kimdoyoung/Desktop/work/gapp/build/unit_tests comparison_funcs  )
set_tests_properties( comparison_funcs PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( is_size /home/kimdoyoung/Desktop/work/gapp/build/unit_tests is_size  )
set_tests_properties( is_size PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( element_at /home/kimdoyoung/Desktop/work/gapp/build/unit_tests element_at  )
set_tests_properties( element_at PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( single_point_crossover /home/kimdoyoung/Desktop/work/gapp/build/unit_tests single_point_crossover  )
set_tests_properties( single_point_crossover PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( two_point_crossover /home/kimdoyoung/Desktop/work/gapp/build/unit_tests two_point_crossover  )
set_tests_properties( two_point_crossover PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( npoint_crossover /home/kimdoyoung/Desktop/work/gapp/build/unit_tests npoint_crossover  )
set_tests_properties( npoint_crossover PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[order1_crossover - int]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[order1_crossover - int]==]  )
set_tests_properties( [==[order1_crossover - int]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[order1_crossover - unsigned]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[order1_crossover - unsigned]==]  )
set_tests_properties( [==[order1_crossover - unsigned]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[order2_crossover - int]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[order2_crossover - int]==]  )
set_tests_properties( [==[order2_crossover - int]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[order2_crossover - unsigned]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[order2_crossover - unsigned]==]  )
set_tests_properties( [==[order2_crossover - unsigned]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[position_crossover - int]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[position_crossover - int]==]  )
set_tests_properties( [==[position_crossover - int]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[position_crossover - unsigned]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[position_crossover - unsigned]==]  )
set_tests_properties( [==[position_crossover - unsigned]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( cycle_crossover /home/kimdoyoung/Desktop/work/gapp/build/unit_tests cycle_crossover  )
set_tests_properties( cycle_crossover PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[edge_crossover - int]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[edge_crossover - int]==]  )
set_tests_properties( [==[edge_crossover - int]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[edge_crossover - unsigned]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[edge_crossover - unsigned]==]  )
set_tests_properties( [==[edge_crossover - unsigned]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[pmx_crossover - int]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[pmx_crossover - int]==]  )
set_tests_properties( [==[pmx_crossover - int]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[pmx_crossover - unsigned]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[pmx_crossover - unsigned]==]  )
set_tests_properties( [==[pmx_crossover - unsigned]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[real_crossover - real::Arithmetic]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[real_crossover - real::Arithmetic]==]  )
set_tests_properties( [==[real_crossover - real::Arithmetic]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[real_crossover - real::BLXa]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[real_crossover - real::BLXa]==]  )
set_tests_properties( [==[real_crossover - real::BLXa]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[real_crossover - real::SimulatedBinary]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[real_crossover - real::SimulatedBinary]==]  )
set_tests_properties( [==[real_crossover - real::SimulatedBinary]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[real_crossover - real::Wright]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[real_crossover - real::Wright]==]  )
set_tests_properties( [==[real_crossover - real::Wright]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( crossover_fitness_eval /home/kimdoyoung/Desktop/work/gapp/build/unit_tests crossover_fitness_eval  )
set_tests_properties( crossover_fitness_eval PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[cone_tree constructors]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[cone_tree constructors]==]  )
set_tests_properties( [==[cone_tree constructors]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( [==[cone_tree lookup]==] /home/kimdoyoung/Desktop/work/gapp/build/unit_tests [==[cone_tree lookup]==]  )
set_tests_properties( [==[cone_tree lookup]==] PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( empty_cone_tree /home/kimdoyoung/Desktop/work/gapp/build/unit_tests empty_cone_tree  )
set_tests_properties( empty_cone_tree PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( hashable /home/kimdoyoung/Desktop/work/gapp/build/unit_tests hashable  )
set_tests_properties( hashable PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( container /home/kimdoyoung/Desktop/work/gapp/build/unit_tests container  )
set_tests_properties( container PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( indexable_container /home/kimdoyoung/Desktop/work/gapp/build/unit_tests indexable_container  )
set_tests_properties( indexable_container PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( increment_mod /home/kimdoyoung/Desktop/work/gapp/build/unit_tests increment_mod  )
set_tests_properties( increment_mod PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( index_vector /home/kimdoyoung/Desktop/work/gapp/build/unit_tests index_vector  )
set_tests_properties( index_vector PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( argsort /home/kimdoyoung/Desktop/work/gapp/build/unit_tests argsort  )
set_tests_properties( argsort PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( partial_argsort /home/kimdoyoung/Desktop/work/gapp/build/unit_tests partial_argsort  )
set_tests_properties( partial_argsort PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( max_element /home/kimdoyoung/Desktop/work/gapp/build/unit_tests max_element  )
set_tests_properties( max_element PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( min_element /home/kimdoyoung/Desktop/work/gapp/build/unit_tests min_element  )
set_tests_properties( min_element PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( argmax /home/kimdoyoung/Desktop/work/gapp/build/unit_tests argmax  )
set_tests_properties( argmax PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( argmin /home/kimdoyoung/Desktop/work/gapp/build/unit_tests argmin  )
set_tests_properties( argmin PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( partial_shuffle /home/kimdoyoung/Desktop/work/gapp/build/unit_tests partial_shuffle  )
set_tests_properties( partial_shuffle PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( contains /home/kimdoyoung/Desktop/work/gapp/build/unit_tests contains  )
set_tests_properties( contains PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( find_all /home/kimdoyoung/Desktop/work/gapp/build/unit_tests find_all  )
set_tests_properties( find_all PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( find_indices /home/kimdoyoung/Desktop/work/gapp/build/unit_tests find_indices  )
set_tests_properties( find_indices PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( index_of /home/kimdoyoung/Desktop/work/gapp/build/unit_tests index_of  )
set_tests_properties( index_of PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( find_index /home/kimdoyoung/Desktop/work/gapp/build/unit_tests find_index  )
set_tests_properties( find_index PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( elementwise_min /home/kimdoyoung/Desktop/work/gapp/build/unit_tests elementwise_min  )
set_tests_properties( elementwise_min PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( elementwise_max /home/kimdoyoung/Desktop/work/gapp/build/unit_tests elementwise_max  )
set_tests_properties( elementwise_max PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( erase_first_stable /home/kimdoyoung/Desktop/work/gapp/build/unit_tests erase_first_stable  )
set_tests_properties( erase_first_stable PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( select /home/kimdoyoung/Desktop/work/gapp/build/unit_tests select  )
set_tests_properties( select PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
add_test( erase_duplicates /home/kimdoyoung/Desktop/work/gapp/build/unit_tests erase_duplicates  )
set_tests_properties( erase_duplicates PROPERTIES WORKING_DIRECTORY /home/kimdoyoung/Desktop/work/gapp/test/unit)
set( unit_tests_TESTS is_same_template is_one_of_templates nth_type is_derived_from_spec_of is_specialization_of is_reverse_iterator dereference remove_rvalue_ref copy_const_t concurrent_queue thread_pool parallel_for nested_parallel_for spinlock shared_spinlock roulette_selection tournament_selection rank_selection [==[sigma_selection[selection][single-objective]]==] [==[boltzmann_selection[selection][single-objective]]==] scope_exit restore_on_exit random_int random_real random_binomial random_idx random_element sample_unique [==[sample_unique_bounds_8 - std::int8_t]==] [==[sample_unique_bounds_8 - std::uint8_t]==] [==[sample_unique_bounds_64 - std::int64_t]==] [==[sample_unique_bounds_64 - std::uint64_t]==] replacement_best replacement_children replacement_elitism [==[reference_lines - quasirandomSimplexPointsMirror]==] [==[reference_lines - quasirandomSimplexPointsSort]==] [==[reference_lines - quasirandomSimplexPointsRoot]==] [==[reference_lines - quasirandomSimplexPointsLog]==] [==[reference_lines_subset - quasirandomSimplexPointsMirror]==] [==[reference_lines_subset - quasirandomSimplexPointsSort]==] [==[reference_lines_subset - quasirandomSimplexPointsRoot]==] [==[reference_lines_subset - quasirandomSimplexPointsLog]==] qrng [==[single_objective_problems - Sphere]==] [==[single_objective_problems - Rastrigin]==] [==[single_objective_problems - Rosenbrock]==] [==[single_objective_problems - Schwefel]==] [==[single_objective_problems - Griewank]==] [==[single_objective_problems - Ackley]==] [==[single_objective_problems - Levy]==] kursawe [==[zdt_suite - ZDT1]==] [==[zdt_suite - ZDT2]==] [==[zdt_suite - ZDT3]==] [==[zdt_suite - ZDT4]==] [==[zdt_suite - ZDT5]==] [==[zdt_suite - ZDT6]==] [==[dtlz_suite - DTLZ1]==] [==[dtlz_suite - DTLZ2]==] [==[dtlz_suite - DTLZ3]==] [==[dtlz_suite - DTLZ4]==] [==[dtlz_suite - DTLZ5]==] [==[dtlz_suite - DTLZ6]==] [==[dtlz_suite - DTLZ7]==] probability merge_pareto_sets find_pareto_front_1D [==[find_pareto_front_nd - findParetoFrontSort]==] [==[find_pareto_front_nd - findParetoFrontBest]==] [==[find_pareto_front_nd - findParetoFrontKung]==] [==[nd_sort - fastNonDominatedSort]==] [==[nd_sort - dominanceDegreeSort]==] mutation_fitness_eval [==[binary_mutation - binary::Flip]==] [==[real_mutation - real::Boundary]==] [==[real_mutation - real::Gauss]==] [==[real_mutation - real::NonUniform]==] [==[real_mutation - real::Polynomial]==] [==[real_mutation - real::Uniform]==] [==[perm_mutation - perm::Inversion]==] [==[perm_mutation - perm::Shift]==] [==[perm_mutation - perm::Shuffle]==] [==[perm_mutation - perm::Swap2]==] [==[perm_mutation - perm::Swap3]==] [==[integer_mutation - integer::Uniform]==] [==[fitness_metrics - FitnessMin]==] [==[fitness_metrics - FitnessMax]==] [==[fitness_metrics - FitnessMean]==] [==[fitness_metrics - FitnessVariance]==] [==[fitness_metrics - FitnessStdDev]==] [==[fitness_metrics - NadirPoint]==] nadir_point_metric hypervolume_metric hypervolume_auto fitness_evaluations matrix matrix_rows matrix_algorithms fp_compare pareto_compare_less pareto_compare_three_way euclidean_norm normalize euclidean_distance perpendicular_distance volume_between integral_sin_pow stable_iterator iota_iterator indestructible hypervolume map flatten arithmetic_funcs comparison_funcs is_size element_at single_point_crossover two_point_crossover npoint_crossover [==[order1_crossover - int]==] [==[order1_crossover - unsigned]==] [==[order2_crossover - int]==] [==[order2_crossover - unsigned]==] [==[position_crossover - int]==] [==[position_crossover - unsigned]==] cycle_crossover [==[edge_crossover - int]==] [==[edge_crossover - unsigned]==] [==[pmx_crossover - int]==] [==[pmx_crossover - unsigned]==] [==[real_crossover - real::Arithmetic]==] [==[real_crossover - real::BLXa]==] [==[real_crossover - real::SimulatedBinary]==] [==[real_crossover - real::Wright]==] crossover_fitness_eval [==[cone_tree constructors]==] [==[cone_tree lookup]==] empty_cone_tree hashable container indexable_container increment_mod index_vector argsort partial_argsort max_element min_element argmax argmin partial_shuffle contains find_all find_indices index_of find_index elementwise_min elementwise_max erase_first_stable select erase_duplicates)
